# .pre-commit-config.yaml
default_language_version:
  python: python3

repos:
  - repo: local
    hooks:
      - id: commit-msg-jira-validator
        name: Commit Message Jira Validator
        entry: .scripts/validate_commit_msg.py
        language: python
        stages: [commit-msg] 
